---
kind: pipeline
name: build and publish
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: ducampsv/rsync-docker
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
